In [22]:
import numpy as np
import pandas as pd

## 2) Crear un vector de ceros de tamaño 10

In [48]:
vector_diez_ceros = np.zeros(10)
print(vector_diez_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [53]:
np.put(vector_diez_ceros, 5, [1])
print(vector_diez_ceros)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.

In [57]:
vector_cincuenta = np.arange(50)
print(vector_cincuenta)
fliped_vector_cincuenta = np.flip(vector_cincuenta)
print(fliped_vector_cincuenta)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 5) Crear una matriz de 3 x 3 con valores del cero al 8

In [21]:
matriz_tres_por_tres = np.arange(9).reshape(3,3)
print(matriz_tres_por_tres)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 6) Encontrar los indices que no sean cero en un arreglo

In [15]:
arreglo = [1,2,0,0,4,0]
my_array = np.array(arreglo)
print(my_array)
indices = my_array.nonzero()
print(indices)

[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


## 7) Crear una matriz de identidad 3 x 3

In [16]:
matriz_identidad_tres_por_tres = np.eye(3)
print(matriz_identidad_tres_por_tres)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 8) Crear una matriz 3 x 3 x 3 con valores randomicos

In [17]:
matriz_3_x_3_x_3 = np.random.rand(3,3,3)
print(matriz_3_x_3_x_3)

[[[0.45597326 0.22665196 0.03648284]
  [0.7352129  0.71236695 0.94568063]
  [0.09601527 0.14247204 0.61449301]]

 [[0.71996144 0.97786558 0.31140854]
  [0.60853538 0.33352586 0.08495123]
  [0.23235826 0.81748755 0.59077321]]

 [[0.27485998 0.82434686 0.25197516]
  [0.77011321 0.60027664 0.42859393]
  [0.49307577 0.16493273 0.136123  ]]]


## 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor

In [20]:
matriz_diez_por_diez = np.arange(100).reshape(10,10)
min = matriz_diez_por_diez.min()
max = matriz_diez_por_diez.max()
print(min)
print(max)

0
99


## 10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

## 11) ¿Como crear una serie de una lista, diccionario o arreglo?

In [58]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
serie_from_list = pd.Series(mylist)
serie_from_array = pd.Series(my_array)
serie_from_dictionary = pd.Series(mydict)
print(serie_from_list)
print(serie_from_array)
print(serie_from_dictionary)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0    1
1    2
2    0
3    0
4    4
5    0
dtype: int32
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


## 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?

In [ ]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# Transformar la serie en dataframe y hacer una columna indice

## 13) ¿Como combinar varias series para hacer un DataFrame?

In [65]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
df = pd.concat([ser2, ser1], axis=1)
df1 = pd.DataFrame({'ser2': ser2,'ser1': ser1})
print(df)
print(df1)

     0  1
0    0  a
1    1  b
2    2  c
3    3  e
4    4  d
5    5  f
6    6  g
7    7  h
8    8  i
9    9  j
10  10  k
11  11  l
12  12  m
13  13  n
14  14  o
15  15  p
16  16  q
17  17  r
18  18  s
19  19  t
20  20  u
21  21  v
22  22  w
23  23  x
24  24  y
25  25  z
    ser2 ser1
0      0    a
1      1    b
2      2    c
3      3    e
4      4    d
5      5    f
6      6    g
7      7    h
8      8    i
9      9    j
10    10    k
11    11    l
12    12    m
13    13    n
14    14    o
15    15    p
16    16    q
17    17    r
18    18    s
19    19    t
20    20    u
21    21    v
22    22    w
23    23    x
24    24    y
25    25    z


## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?

In [67]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

## 15) ¿Como obtener los items que no son comunes en una serie A y serie B?

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

## 16) ¿Como obtener el numero de veces que se repite un valor en una serie?

In [32]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
numero_veces = ser.value_counts()
print(numero_veces)

e    8
g    6
c    5
f    3
d    3
a    2
h    2
b    1
dtype: int64


## 17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

In [34]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un shape definido?

In [71]:
ser = pd.Series(np.random.randint(1, 10, 35))
shape(7,5)

AttributeError: 'Series' object has no attribute 'reshape'

## 19) ¿Obtener los valores de una serie conociendo la posicion por indice?

In [36]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u
my_serie = ser[pos]
print(my_serie)

0     a
4     e
8     i
14    o
20    u
dtype: object


## 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?

In [39]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

## 21) ¿Obtener la media de una serie agrupada por otra serie?

In [47]:
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

# Los valores van a cambiar por ser random
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64
media = pesos.mean()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['manzana', 'manzana', 'zanahoria', 'banana', 'zanahoria', 'manzana', 'manzana', 'zanahoria', 'banana', 'zanahoria']


## 22) ¿Como importar solo columnas especificas de un archivo csv?

In [46]:
csv_path = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'
df = pd.read_csv(csv_path, usecols = ['crim', 'zn'])
print(df)

         crim    zn
0     0.00632  18.0
1     0.02731   0.0
2     0.02729   0.0
3     0.03237   0.0
4     0.06905   0.0
5     0.02985   0.0
6     0.08829  12.5
7     0.14455  12.5
8     0.21124  12.5
9     0.17004  12.5
10    0.22489  12.5
11    0.11747  12.5
12    0.09378  12.5
13    0.62976   0.0
14    0.63796   0.0
15    0.62739   0.0
16    1.05393   0.0
17    0.78420   0.0
18    0.80271   0.0
19    0.72580   0.0
20    1.25179   0.0
21    0.85204   0.0
22    1.23247   0.0
23    0.98843   0.0
24    0.75026   0.0
25    0.84054   0.0
26    0.67191   0.0
27    0.95577   0.0
28    0.77299   0.0
29    1.00245   0.0
..        ...   ...
476   4.87141   0.0
477  15.02340   0.0
478  10.23300   0.0
479  14.33370   0.0
480   5.82401   0.0
481   5.70818   0.0
482   5.73116   0.0
483   2.81838   0.0
484   2.37857   0.0
485   3.67367   0.0
486   5.69175   0.0
487   4.83567   0.0
488   0.15086   0.0
489   0.18337   0.0
490   0.20746   0.0
491   0.10574   0.0
492   0.11132   0.0
493   0.17331   0.0
